config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events
  resources :item_groups
  resources :item_taggings
  resources :item_tags
  devise_for :users
  namespace :admin do
    resources :users
  end
  resources :standardizations
  resources :items
  resources :periods do
    resources :evaluation_targets,
              shallow: true,
              only: [:index, :show, :create, :destroy] do
      resources :assignments,
                shallow: true,
                only: [:create, :destroy] do
        resources :evaluations, only: [:index, :show, :edit, :update] do
          collection do
            post "synchronize"
          end
        end
      end
      resources :objectives, only: [:create, :destroy]
      resources :final_evaluations, only: [:index, :show, :edit, :update] do
        collection do
          post "synchronize"
        end
      end
      resources :evaluation_reports,
                shallow: true,
                except: [:index]
    end
  end
  resources :standards
  root "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :participants, dependent: :destroy
  has_many :users, -> {active.order(:id)}, through: :participants
  accepts_nested_attributes_for :participants, allow_destroy: true

  def available_participants
    User.active.order(:id).collect do |user|
      Participant.find_or_initialize_by(event_id: id,
                                        user_id: user.id)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include Pagy::Backend

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    events = Event.order(occurred_at: :desc)
    user_id = user_id_param
    if user_id
      events = events.joins(:participants).where(participants: {user_id: user_id})
    end
    @pagy, @events = pagy(events)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title,
                                    :url,
                                    :occurred_at,
                                    :description,
                                    {
                                      participants_attributes: [
                                        :id,
                                        :event_id,
                                        :user_id,
                                        :_destroy,
                                      ],
                                    })
    end

    def user_id_param
      user_id = params[:user_id]
      return nil if user_id.nil?

      begin
        Integer(user_id, 10)
      rescue ArgumentError
        nil
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
  include Pagy::Frontend
end

app/views/events/_form.html.erb
<div class="box">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <div class="control">
        <%= form.text_field :title %>
      </div>
    </div>

    <div class="field">
      <%= form.label :url %>
      <div class="control">
        <%= form.text_field :url %>
      </div>
    </div>

    <div class="field">
      <%= form.label :occurred_at %>
      <div class="control">
        <%= form.datetime_select :occurred_at, default: Date.current %>
      </div>
    </div>

    <div class="field">
      <%= form.label :description %>
      <div class="control">
        <%= form.text_area :description %>
      </div>
    </div>

    <div class="field">
      <%= form.label :participants %>
      <table>
        <thead>
          <tr>
            <th><%= User.human_attribute_name("name") %></th>
            <th><%= t("actions.select") %></th>
          </tr>
        </thead>

        <tbody>
          <%= form.fields_for(
                :participants,
                event.available_participants) do |participant_fields| -%>
            <% user = participant_fields.object.user -%>
            <tr>
              <td><%= user.name %></td>
              <td>
                <%= participant_fields.hidden_field(:event_id) %>
                <%= participant_fields.hidden_field(:user_id) %>
                <%= participant_fields.check_box(
                      :_destroy,
                      {checked: participant_fields.object.persisted?},
                      "0",
                      "1") %>
              </td>
            </tr>
          <% end -%>
        </tbody>
      </table>
    </div>

    <div class="field is-grouped">
      <div class="control">
        <%= form.submit class: "is-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/_index.html.erb
<h3><%= Event.model_name.human_plural %></h3>

<table>
  <thead>
    <tr>
      <th><%= Event.human_attribute_name("id") %></th>
      <th><%= Event.human_attribute_name("title") %></th>
      <th><%= Event.human_attribute_name("url") %></th>
      <th><%= Event.human_attribute_name("occurred_at") %></th>
      <th><%= Event.human_attribute_name("description") %></th>
      <th><%= Event.human_attribute_name("participants") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= link_to(event.id, event) %></td>
        <td><%= event.title %></td>
        <td><%= link_to(event.url, event.url) %></td>
        <td><%= event.occurred_at %></td>
        <td><%= render_markdown(event.description) %></td>
        <td>
          <ul>
            <% event.users.each do |user| -%>
              <li><%= user.name %></li>
            <% end -%>
          </ul>
        </td>
        <td><%= link_to(t("actions.show"), event) %></td>
        <td><%= link_to(t("actions.edit"), edit_event_path(event)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/edit.html.erb
<h1><%= t(".title", default: "Editing Event") %></h1>

<%= render 'form', event: @event %>

<div class="box">
  <div class="columns">
    <div class="column">
      <%= link_to t("actions.show"), @event %>
    </div>
    <div class="column">
      <%= link_to t("actions.back"), events_path %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<h1><%= t(".title", default: Event.model_name.human_plural) %></h1>

<div class="box">
  <div class="columns">
    <div class="column">
      <%= link_to t("actions.new", model: Event.model_name.human), new_event_path %>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th><%= Event.human_attribute_name("title") %></th>
      <th><%= Event.human_attribute_name("url") %></th>
      <th><%= Event.human_attribute_name("occurred_at") %></th>
      <th><%= Event.human_attribute_name("description") %></th>
      <th><%= Event.human_attribute_name("participants") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= link_to event.url, event.url %></td>
        <td><%= event.occurred_at %></td>
        <td><%= render_markdown(event.description) %></td>
        <td>
          <ul>
            <% event.users.each do |user| -%>
              <li><%= link_to(user.name, events_path(user_id: user.id)) %></li>
            <% end -%>
          </ul>
        </td>
        <td><%= link_to t("actions.show"), event %></td>
        <td><%= link_to t("actions.edit"), edit_event_path(event) %></td>
        <td><%= link_to t("actions.destroy"),
                        event,
                        data: {
                          turbo_confirm: t("messages.confirmations.destroy"),
                          turbo_method: :delete,
                        } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_nav(@pagy) if @pagy.pages > 1 %>

<div class="box">
  <div class="columns">
    <div class="column">
      <%= link_to t("actions.new", model: Event.model_name.human), new_event_path %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h1><%= t(".title", default: t("actions.new", model: Event.model_name.human)) %></h1>

<%= render 'form', event: @event %>

<div class="box">
  <div class="columns">
    <div class="column">
      <%= link_to t("actions.back"), events_path %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

<div class="box">
  <h2><%= Event.human_attribute_name("url") %></h2>
  <p>
    <%= link_to @event.url, @event.url %>
  </p>

  <h2><%= Event.human_attribute_name("occurred_at") %></h2>
  <p>
    <%= @event.occurred_at %>
  </p>

  <h2><%= Event.human_attribute_name("description") %></h2>
  <p>
    <%= render_markdown(@event.description) %>
  </p>

  <h2><%= Event.human_attribute_name("participants") %></h2>
  <ul>
    <% @event.users.each do |user| -%>
      <li><%= user.name %></li>
    <% end -%>
  </ul>
</div>

<div class="box">
  <div class="columns">
    <div class="column">
      <%= link_to t("actions.edit"), edit_event_path(@event) %>
    </div>
    <div class="column">
      <%= link_to t("actions.back"), events_path %>
    </div>
  </div>
</div>