config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events
  resources :item_groups
  resources :item_taggings
  resources :item_tags
  devise_for :users
  namespace :admin do
    resources :users
  end
  resources :standardizations
  resources :items
  resources :periods do
    resources :evaluation_targets,
              shallow: true,
              only: [:index, :show, :create, :destroy] do
      resources :assignments,
                shallow: true,
                only: [:create, :destroy] do
        resources :evaluations, only: [:index, :show, :edit, :update] do
          collection do
            post "synchronize"
          end
        end
      end
      resources :objectives, only: [:create, :destroy]
      resources :final_evaluations, only: [:index, :show, :edit, :update] do
        collection do
          post "synchronize"
        end
      end
      resources :evaluation_reports,
                shallow: true,
                except: [:index]
    end
  end
  resources :standards
  root "events#index"
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_taggings, dependent: :destroy
  has_many :item_tags, -> {order(:name)}, through: :item_taggings
  belongs_to :item_group
  has_many :standardizations, dependent: :destroy
  has_many :standards, through: :standardizations
  has_many :evaluations, dependent: :destroy
  has_many :final_evaluations, dependent: :destroy
  accepts_nested_attributes_for :item_taggings, allow_destroy: true

  validates :item_group, presence: true

  def available_item_taggings
    ItemTag.all.order(:name).collect do |item_tag|
      ItemTagging.find_or_initialize_by(item_id: id,
                                        item_tag_id: item_tag.id)
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.
               all.
               order(:id).
               includes(:item_tags, :standards)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name,
                                   :reason,
                                   :example,
                                   :note,
                                   :item_group_id,
                                   {
                                     item_taggings_attributes: [
                                       :id,
                                       :item_id,
                                       :item_tag_id,
                                       :_destroy,
                                     ],
                                   })
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="box">
  <%= form_with(model: item, local: true) do |form| %>
    <% if item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
          <% item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <div class="control">
        <%= form.text_field :name %>
      </div>
    </div>

    <div class="field">
      <%= form.label :reason %>
      <div class="control">
        <%= form.text_area :reason %>
      </div>
    </div>

    <div class="field">
      <%= form.label :example %>
      <div class="control">
        <%= form.text_area :example %>
      </div>
    </div>

    <div class="field">
      <%= form.label :note %>
      <div class="control">
        <%= form.text_area :note %>
      </div>
    </div>

    <div class="field">
      <%= form.label :note %>
      <div class="control">
        <%= form.select :item_group_id, ItemGroup.all.collect {|g| [g.name, g.id]} %>
      </div>
    </div>

    <div class="field">
      <%= form.label :item_tags %>

      <table>
        <thead>
          <tr>
            <th><%= ItemTag.human_attribute_name("name") %></th>
            <th><%= t("actions.select") %></th>
          </tr>
        </thead>

        <tbody>
          <%= form.fields_for(
                :item_taggings,
                item.available_item_taggings) do |item_tagging_fields| -%>
            <% item_tag = item_tagging_fields.object.item_tag -%>
            <tr>
              <td><%= item_tag.name %></td>
              <td>
                <%= item_tagging_fields.hidden_field(:item_id) %>
                <%= item_tagging_fields.hidden_field(:item_tag_id) %>
                <%= item_tagging_fields.check_box(
                      :_destroy,
                      {checked: item_tagging_fields.object.persisted?},
                      "0",
                      "1") %>
              </td>
            </tr>
          <% end -%>
        </tbody>
      </table>
    </div>

    <div class="field is-grouped">
      <div class="control">
        <%= form.submit class: "is-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/_index.html.erb
<h3><%= local_assigns[:title] ? title : Item.model_name.human_plural %></h3>
<table>
  <thead>
    <tr>
      <th><%= Item.human_attribute_name("id") %></th>
      <th><%= Item.human_attribute_name("name") %></th>
      <th><%= Item.human_attribute_name("reason") %></th>
      <th><%= Item.human_attribute_name("example") %></th>
      <th><%= Item.human_attribute_name("note") %></th>
      <th><%= Item.human_attribute_name("item_group") %></th>
      <th><%= Item.human_attribute_name("item_tags") %></th>
      <th><%= Item.human_attribute_name("standards") %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= render_markdown(item.reason) %></td>
        <td><%= render_markdown(item.example) %></td>
        <td><%= render_markdown(item.note) %></td>
        <td><%= link_to(item.item_group.name, item.item_group) %></td>
        <td>
          <ul>
            <% item.item_tags.each do |item_tag| -%>
            <li><%= link_to(item_tag.name, item_tag) %></li>
            <% end -%>
          </ul>
        </td>
        <td>
          <ul>
            <% item.standards.each do |standard| -%>
              <li><%= link_to(standard.name, standard) %></li>
            <% end -%>
          </ul>
        </td>
        <td><%= link_to t("actions.show"), item %></td>
        <td><%= link_to t("actions.edit"), edit_item_path(item) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Markdown</h3>
<pre>
<% items.each do |item| -%>
* <%= item.id %>: <%= item.name %>
  <% item.item_tags.each do |item_tag| -%>
  * <%= item_tag.name %>
  <% end -%>
<% end -%>
</pre>

app/views/items/_show.html.erb
<div class="item-name">
  <h2><%= link_to("#{item.id}: #{item.name}", item) %></h2>
</div>
<div class="item-reason">
  <h3><%= Item.human_attribute_name("reason") %></h3>
  <%= render_markdown(item.reason) %>
</div>
<div class="item-example">
  <h3><%= Item.human_attribute_name("example") %></h3>
  <%= render_markdown(item.example) %>
</div>
<div class="item-note">
  <h3><%= Item.human_attribute_name("note") %></h3>
  <%= render_markdown(item.note) %>
</div>
<div class="item-group">
  <h3><%= Item.human_attribute_name("item_group") %></h3>
  <p><%= link_to(item.item_group.name, item.item_group) %></p>
</div>
<div class="item-tags">
  <h3><%= Item.human_attribute_name("item_tags") %></h3>
  <ul>
    <% item.item_tags.each do |item_tag| %>
      <li><%= link_to(item_tag.name, item_tag) %></li>
    <% end %>
  </ul>
</div>

app/views/items/edit.html.erb
<h1><%= t(".title", default: "Editing Item") %></h1>

<div class="box">
  <div class="columns">
    <div class="column">
      <%= link_to t("actions.show"), @item %>
    </div>
    <div class="column">
      <%= link_to t("actions.back"), items_path %>
    </div>
  </div>
</div>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<h1><%= t(".title", default: Item.model_name.human_plural) %></h1>

<div class="box">
  <div class="columns">
    <div class="column">
      <%= link_to t("actions.new", model: Item.model_name.human), new_item_path %>
    </div>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th><%= Item.human_attribute_name("id") %></th>
      <th><%= Item.human_attribute_name("name") %></th>
      <th><%= Item.human_attribute_name("reason") %></th>
      <th><%= Item.human_attribute_name("example") %></th>
      <th><%= Item.human_attribute_name("note") %></th>
      <th><%= Item.human_attribute_name("item_group") %></th>
      <th><%= Item.human_attribute_name("item_tags") %></th>
      <th><%= Standard.model_name.human_plural %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= item.name %></td>
        <td><%= render_markdown(item.reason) %></td>
        <td><%= render_markdown(item.example) %></td>
        <td><%= render_markdown(item.note) %></td>
        <td><%= link_to(item.item_group.name, item.item_group) %></td>
        <td>
          <ul>
            <% item.item_tags.each do |item_tag| -%>
              <li><%= link_to(item_tag.name, item_tag) %></li>
            <% end -%>
          </ul>
        </td>
        <td>
          <ul>
            <% item.standards.each do |standard| -%>
              <li><%= link_to(standard.name, standard) %></li>
            <% end -%>
          </ul>
        </td>
        <td><%= link_to t("actions.show"), item %></td>
        <td><%= link_to t("actions.edit"), edit_item_path(item) %></td>
        <td><%= link_to t("actions.destroy"),
                        item,
                        data: {
                          turbo_confirm: t("actions.confirmations.destroy"),
                          turbo_method: :delete,
                        } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="box">
  <div class="columns">
    <div class="column">
      <%= link_to t("actions.new", model: Item.model_name.human), new_item_path %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1><%= t(".title", default: t("actions.new", model: Item.model_name.human)) %></h1>

<%= render 'form', item: @item %>

<%= link_to t("actions.back"), items_path %>

app/views/items/show.html.erb
<h1><%= @item.id %>: <%= @item.name %></h1>

<div class="box">
  <div class="columns">
    <div class="column">
      <%= link_to t("actions.edit"), edit_item_path(@item) %>
    </div>
    <div class="column">
      <%= link_to t("actions.back"), items_path %>
    </div>
  </div>
</div>

<div class="box">
  <h2><%= Item.human_attribute_name("reason") %></h2>
  <div class="box"><%= render_markdown(@item.reason) %></div>

  <h2><%= Item.human_attribute_name("example") %></h2>
  <div class="box"><%= render_markdown(@item.example) %></div>

  <h2><%= Item.human_attribute_name("note") %></h2>
  <div class="box"><%= render_markdown(@item.note) %></div>

  <h2><%= Item.human_attribute_name("item_group") %></h2>
  <p><%= link_to(@item.item_group.name, @item.item_group) %></p>

  <h2><%= Item.human_attribute_name("item_tags") %></h2>
  <table>
    <thead>
      <tr>
        <th><%= ItemTag.human_attribute_name("name") %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @item.item_tags.each do |item_tag| %>
      <tr>
        <td><%= item_tag.name %></td>
        <td><%= link_to t("actions.show"), item_tag %></td>
        <td><%= link_to t("actions.edit"), edit_item_tag_path(item_tag) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>