config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events
  resources :item_groups
  resources :item_taggings
  resources :item_tags
  devise_for :users
  namespace :admin do
    resources :users
  end
  resources :standardizations
  resources :items
  resources :periods do
    resources :evaluation_targets,
              shallow: true,
              only: [:index, :show, :create, :destroy] do
      resources :assignments,
                shallow: true,
                only: [:create, :destroy] do
        resources :evaluations, only: [:index, :show, :edit, :update] do
          collection do
            post "synchronize"
          end
        end
      end
      resources :objectives, only: [:create, :destroy]
      resources :final_evaluations, only: [:index, :show, :edit, :update] do
        collection do
          post "synchronize"
        end
      end
      resources :evaluation_reports,
                shallow: true,
                except: [:index]
    end
  end
  resources :standards
  root "events#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :confirmable,
         :database_authenticatable,
         :lockable,
         :recoverable,
         # TODO
         # :registerable,
         :rememberable,
         :trackable,
         :validatable,
         lock_strategy: :none,
         unlock_strategy: :none

  has_many :evaluation_targets,
           foreign_key: "evaluatee_id",
           dependent: :destroy
  has_many :evaluation_reports,
           through: :evaluation_targets
  has_many :evaluatee_periods,
           -> {distinct},
           through: :evaluation_targets,
           source: :period,
           class_name: "Period"
  has_many :evaluator_assignments,
           foreign_key: "evaluator_id",
           class_name: "Assignment",
           dependent: :destroy
  has_many :evaluator_periods,
           -> {distinct},
           through: :evaluator_assignments,
           source: :period,
           class_name: "Period"
  has_many :participants, dependent: :destroy
  has_many :events, through: :participants

  scope :active, -> { where(locked_at: nil) }

  def initialize(*args)
    super
    if User.count.zero?
      self.admin = true
    else
      self.locked_at = Time.now.utc
    end
  end

  def display_name
    name || email[/\A[^@]+/, 0]
  end

  def all_periods_final_summary_values
    all_periods_summary_values = {}
    FinalEvaluation.
      joins(evaluation_target: [], item: :item_tags).
      where(evaluation_target: {evaluatee: self}).
      group("evaluation_target_id",
            "item_tag_id").
      select("evaluation_target_id",
             "item_tag_id",
             "sum(value) as total_value").
      each do |final_evaluation|
      target = final_evaluation.evaluation_target
      summary_values = (all_periods_summary_values[target.period_id] ||= {})
      summary_values[final_evaluation.item_tag_id] = final_evaluation.total_value
    end
    all_periods_summary_values
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin
  before_action :set_user, only: [:show, :edit, :update]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.all.order(:id)
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(user_create_params)
    @user.password = SecureRandom.base64
    @user.password_confirmation = @user.password

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_url(@user),
                                  notice: 'User was successfully created.' }
        format.json { render :show,
                             status: :created,
                             location: admin_user_path(@user) }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      _params = user_update_params
      if _params.delete(:access_locked) == "1"
        _params[:locked_at] = Time.now
      else
        _params[:locked_at] = nil
      end
      if @user.update(_params)
        format.html { redirect_to admin_user_url(@user),
                                  notice: 'User was successfully updated.' }
        format.json { render :show,
                             status: :ok,
                             location: admin_user_path(@user) }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_create_params
    params.require(:user).permit(:admin, :email, :name)
  end

  def user_update_params
    params.require(:user).permit(:access_locked, :admin, :name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user], local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, readonly: user.persisted? %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="field">
    <%= form.label :access_locked %>
    <%= form.check_box :access_locked? %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1><%= t(".title", default: "Editing User") %></h1>

<%= render 'form', user: @user %>

<%= link_to t("actions.edit"), admin_user_path(@user) %> |
<%= link_to t("actions.back"), admin_users_path %>

app/views/admin/users/index.html.erb
<h1><%= t(".title", default: User.model_name.human_plural) %></h1>

<table>
  <thead>
    <tr>
      <th>Eメール</th>
      <th>名前</th>
      <th>管理者</th>
      <th>登録日時</th>
      <th>更新日時</th>
      <th>ロック日時</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.admin? %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= user.locked_at %></td>
        <td><%= link_to t("actions.show"), admin_user_path(user) %></td>
        <td><%= link_to t("actions.edit"), edit_admin_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("actions.new", model: User.model_name.human), new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1><%= t(".title", default: t("actions.new", model: User.model_name.human)) %></h1>

<%= render 'form', user: @user %>

<%= link_to t("actions.back"), admin_users_path %>

app/views/admin/users/show.html.erb
<p>
  <strong>Eメール:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>管理者:</strong>
  <%= @user.admin? %>
</p>

<%= link_to t("actions.edit"), edit_admin_user_path(@user) %> |
<%= link_to t("actions.back"), admin_users_path %>