config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events
  resources :item_groups
  resources :item_taggings
  resources :item_tags
  devise_for :users
  namespace :admin do
    resources :users
  end
  resources :standardizations
  resources :items
  resources :periods do
    resources :evaluation_targets,
              shallow: true,
              only: [:index, :show, :create, :destroy] do
      resources :assignments,
                shallow: true,
                only: [:create, :destroy] do
        resources :evaluations, only: [:index, :show, :edit, :update] do
          collection do
            post "synchronize"
          end
        end
      end
      resources :objectives, only: [:create, :destroy]
      resources :final_evaluations, only: [:index, :show, :edit, :update] do
        collection do
          post "synchronize"
        end
      end
      resources :evaluation_reports,
                shallow: true,
                except: [:index]
    end
  end
  resources :standards
  root "events#index"
end

app/models/standardization.rb
class Standardization < ApplicationRecord
  belongs_to :standard
  belongs_to :item
end

app/controllers/standardizations_controller.rb
class StandardizationsController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_standardization, only: [:show, :edit, :update, :destroy]

  # GET /standardizations
  # GET /standardizations.json
  def index
    @standardizations = Standardization.all
  end

  # GET /standardizations/1
  # GET /standardizations/1.json
  def show
  end

  # GET /standardizations/new
  def new
    @standardization = Standardization.new
  end

  # GET /standardizations/1/edit
  def edit
  end

  # POST /standardizations
  # POST /standardizations.json
  def create
    @standardization = Standardization.new(standardization_params)

    respond_to do |format|
      if @standardization.save
        format.html { redirect_to @standardization, notice: 'Standardization was successfully created.' }
        format.json { render :show, status: :created, location: @standardization }
      else
        format.html { render :new }
        format.json { render json: @standardization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /standardizations/1
  # PATCH/PUT /standardizations/1.json
  def update
    respond_to do |format|
      if @standardization.update(standardization_params)
        format.html { redirect_to @standardization, notice: 'Standardization was successfully updated.' }
        format.json { render :show, status: :ok, location: @standardization }
      else
        format.html { render :edit }
        format.json { render json: @standardization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standardizations/1
  # DELETE /standardizations/1.json
  def destroy
    @standardization.destroy
    respond_to do |format|
      format.html { redirect_to standardizations_url, notice: 'Standardization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_standardization
      @standardization = Standardization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def standardization_params
      params.require(:standardization).permit(:standard_id, :item_id)
    end
end

app/helpers/standardizations_helper.rb
module StandardizationsHelper
end

app/views/standardizations/_form.html.erb
<%= form_with(model: standardization, local: true) do |form| %>
  <% if standardization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(standardization.errors.count, "error") %> prohibited this standardization from being saved:</h2>

      <ul>
        <% standardization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :standard_id %>
    <%= form.text_field :standard_id %>
  </div>

  <div class="field">
    <%= form.label :item_id %>
    <%= form.text_field :item_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/standardizations/edit.html.erb
<h1><%= t(".title", default: "Editing Standardization") %></h1>

<%= render 'form', standardization: @standardization %>

<%= link_to t("actions.show"), @standardization %> |
<%= link_to t("actions.back"), standardizations_path %>

app/views/standardizations/index.html.erb
<h1><%= t(".title", default: Standardization.model_name.human_plural) %></h1>

<table>
  <thead>
    <tr>
      <th>Standard</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @standardizations.each do |standardization| %>
      <tr>
        <td><%= standardization.standard_id %></td>
        <td><%= standardization.item_id %></td>
        <td><%= link_to t("actions.show"), standardization %></td>
        <td><%= link_to t("actions.edit"), edit_standardization_path(standardization) %></td>
        <td><%= link_to t("actions.destroy"),
                        standardization,
                        data: {
                          turbo_confirm: t("actions.confirmations.destroy"),
                          turbo_method: :delete,
                        } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("actions.new", model: Standardization.model_name.human), new_standardization_path %>

app/views/standardizations/new.html.erb
<h1><%= t(".title", default: t("actions.new", model: Standardization.model_name.human)) %></h1>

<%= render 'form', standardization: @standardization %>

<%= link_to t("actions.back"), standardizations_path %>

app/views/standardizations/show.html.erb
<p>
  <strong>Standard:</strong>
  <%= @standardization.standard_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @standardization.item_id %>
</p>

<%= link_to t("actions.edit"), edit_standardization_path(@standardization) %> |
<%= link_to t("actions.back"), standardizations_path %>